In [12]:
#load data (after segmentation)
import numpy as np
import pandas as pd
dataset = pd.read_csv('1.data.csv')

In [13]:
#Separate data and targets
dataColumns=len(dataset.columns)
X=dataset.iloc[:,0:dataColumns-1].values
y=dataset.iloc[:,dataColumns-1].values

In [14]:
print(X.shape)
print(y.shape)

(29135, 300)
(29135,)


In [15]:
#View data in numbers
print(X[0:5])
print(y[0:5])

[[-0.16709333 -0.16459333 -0.16359333 ...  0.00965833  0.00665833
   0.00415833]
 [ 0.          0.          0.         ... -0.07235    -0.07035
  -0.06985   ]
 [-0.04135    -0.04285    -0.04585    ... -0.01767    -0.02017
  -0.02167   ]
 [ 0.01183     0.00733     0.00433    ...  0.00448167  0.00048167
  -0.00401833]
 [ 0.02848167  0.02098167  0.01498167 ...  0.088015    0.084515
   0.079515  ]]
['V' '/' '/' '/' '/']


In [16]:
#Data visualization
import matplotlib.pyplot as plt
plt.plot(X[0])

In [17]:
#Taking 5000 datasamples for each target class
numDataPerClass=5000

data1=np.zeros((numDataPerClass,dataColumns-1),dtype=float)
target1=np.zeros((numDataPerClass,1),dtype=float)

data2=np.zeros((numDataPerClass,dataColumns-1),dtype=float)
target2=np.zeros((numDataPerClass,1),dtype=float)

data3=np.zeros((numDataPerClass,dataColumns-1),dtype=float)
target3=np.zeros((numDataPerClass,1),dtype=float)

data5=np.zeros((numDataPerClass,dataColumns-1),dtype=float)
target5=np.zeros((numDataPerClass,1),dtype=float)

data12=np.zeros((numDataPerClass,dataColumns-1),dtype=float)
target12=np.zeros((numDataPerClass,1),dtype=float)

i=0;
count1=0
count2=0
count3=0
count5=0
count12=0

while ((count1+count2+count3+count5+count12)<numDataPerClass*5):
    if(y[i]=='N' and count1<numDataPerClass):#Normal Data
        data1[count1,:]=X[i,:]
        target1[count1,:]=0
        count1=count1+1
    elif(y[i]=='/' and count2<numDataPerClass):#Paced beats
        data2[count2,:]=X[i,:]
        target2[count2,:]=1
        count2=count2+1
    elif(y[i]=='R' and count3<numDataPerClass):#Right Bundle Branch Block
        data3[count3,:]=X[i,:]
        target3[count3,:]=2
        count3=count3+1
    elif(y[i]=='L' and count5<numDataPerClass):#Left Bundle Branch Block
        data5[count5,:]=X[i,:]
        target5[count5,:]=3
        count5=count5+1
    elif(y[i]=='V' and count12<numDataPerClass):#Ventricular
        data12[count12,:]=X[i,:]
        target12[count12,:]=4
        count12=count12+1
    i=i+1

data=np.concatenate((data1,data2,data3,data5,data12),axis=0)
target=np.concatenate((target1,target2,target3,target5,target12),axis=0)



In [18]:
#View current variables in memory
%who

X	 count1	 count12	 count2	 count3	 count5	 data	 data1	 data12	 
data2	 data3	 data5	 dataColumns	 dataset	 i	 np	 np_utils	 numDataPerClass	 
pd	 plt	 target	 target1	 target12	 target2	 target3	 target5	 testX	 
testY	 trainX	 trainY	 train_test_split	 y	 


In [19]:
#delete unneccessary variables
del data1, data2, data3, data5, data12
del target1, target2, target3, target5, target12
del i, count1, count2, count3, count5, count12

In [20]:
#View current variables in memory (with some extra information)
%whos

Variable           Type         Data/Info
-----------------------------------------
X                  ndarray      29135x300: 8740500 elems, type `float64`, 69924000 bytes (66.68472290039062 Mb)
data               ndarray      25000x300: 7500000 elems, type `float64`, 60000000 bytes (57.220458984375 Mb)
dataColumns        int          301
dataset            DataFrame                  0       0.1<...>29135 rows x 301 columns]
np                 module       <module 'numpy' from 'C:\<...>ges\\numpy\\__init__.py'>
np_utils           module       <module 'keras.utils.np_u<...>ras\\utils\\np_utils.py'>
numDataPerClass    int          5000
pd                 module       <module 'pandas' from 'C:<...>es\\pandas\\__init__.py'>
plt                module       <module 'matplotlib.pyplo<...>\\matplotlib\\pyplot.py'>
target             ndarray      25000x1: 25000 elems, type `float64`, 200000 bytes (195.3125 kb)
testX              ndarray      7500x300: 2250000 elems, type `float64`, 18000000 by

In [21]:
#split data into 70(training):30(testing) ratio
from sklearn.model_selection import train_test_split
trainX,testX,trainY,testY=train_test_split(data,target,test_size=0.30)

In [22]:
print('Before one-hot encoding')
print(trainY.shape)
print(testY.shape)

#convert to one-hot encoding
from keras.utils import np_utils

trainY=np_utils.to_categorical(trainY)
testY=np_utils.to_categorical(testY)
print('After one-hot encoding')
print(trainY.shape)
print(testY.shape)

Before one-hot encoding
(17500, 1)
(7500, 1)
After one-hot encoding
(17500, 5)
(7500, 5)


In [23]:
print('First target vector in training data \t'+str(trainY[0]))
print('First target vector in testing data \t'+str(testY[0]))

First target vector in training data 	[1. 0. 0. 0. 0.]
First target vector in testing data 	[0. 0. 0. 0. 1.]


In [24]:
#inport libraries necessary for keras models and layers
import keras
from keras.models import *
from keras.layers import *

#Make Artificial neural network
classifier = Sequential()
classifier.add(Dense(units = 152, kernel_initializer = 'uniform', activation = 'relu', input_dim = 300))
classifier.add(Dense(units = 300, kernel_initializer = 'uniform', activation = 'relu'))
classifier.add(Dense(units = 300, kernel_initializer = 'uniform', activation = 'relu'))
classifier.add(Dense(units = 152, kernel_initializer = 'uniform', activation = 'relu'))
classifier.add(Dense(units = 5, kernel_initializer = 'uniform', activation = 'softmax'))

classifier.compile(optimizer = 'adam', loss = 'categorical_crossentropy', metrics = ['accuracy'])

In [25]:
classifier.summary()

_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_1 (Dense)              (None, 152)               45752     
_________________________________________________________________
dense_2 (Dense)              (None, 300)               45900     
_________________________________________________________________
dense_3 (Dense)              (None, 300)               90300     
_________________________________________________________________
dense_4 (Dense)              (None, 152)               45752     
_________________________________________________________________
dense_5 (Dense)              (None, 5)                 765       
Total params: 228,469
Trainable params: 228,469
Non-trainable params: 0
_________________________________________________________________


In [26]:
#training a classifier i.e. making it learn to differentiate between 1 normal and 4 abnormal classes
classifier.fit(trainX, trainY, batch_size = 100, epochs = 10, verbose=1,
          validation_data=(testX, testY))

Instructions for updating:
Use tf.where in 2.0, which has the same broadcast rule as np.where

Train on 17500 samples, validate on 7500 samples
Epoch 1/10
17500/17500 [==============================] - 7s 423us/step - loss: 0.3078 - acc: 0.9001 - val_loss: 0.0794 - val_acc: 0.9751
Epoch 2/10
17500/17500 [==============================] - 2s 127us/step - loss: 0.0658 - acc: 0.9818 - val_loss: 0.0579 - val_acc: 0.9857
Epoch 3/10
17500/17500 [==============================] - 2s 131us/step - loss: 0.0412 - acc: 0.9881 - val_loss: 0.0448 - val_acc: 0.9876
Epoch 4/10
17500/17500 [==============================] - 2s 130us/step - loss: 0.0326 - acc: 0.9917 - val_loss: 0.0374 - val_acc: 0.9903
Epoch 5/10
17500/17500 [==============================] - 2s 128us/step - loss: 0.0318 - acc: 0.9912 - val_loss: 0.0359 - val_acc: 0.9896
Epoch 6/10
17500/17500 [==============================] - 2s 140us/step - loss: 0.0220 - acc: 0.9936 - val_loss: 0.0379 - val_acc: 0.9887
Epoch 7/10
17500/17500 [====

In [27]:
#save trained classifier for future
classifier.save('classifier.h5')

In [28]:
score = classifier.evaluate(testX, testY, verbose=0)
print('Test loss:', score[0])
print('Test accuracy:', score[1])

Test loss: 0.04840311065988305
Test accuracy: 0.9896000000317892


In [29]:
from sklearn.metrics import classification_report,confusion_matrix

predY=classifier.predict(testX)
predY=np.argmax(predY,axis=1)
testY1=np.argmax(testY,axis=1)

                        #Compute Confusion Matrix
cm=confusion_matrix(testY1,predY)
np.set_printoptions(precision=2)
print('Confusion matrix, without normalization')
print(cm)
                        #Compute Normalized Confusion Matrix
cm_normalized=cm.astype('float')/cm.sum(axis=1)[:, np.newaxis]
print('Normalized confusion matrix')
print(cm_normalized)

                        #ANN  Classification report
ann_classification_report=classification_report(testY1,predY)
print(ann_classification_report)

Confusion matrix, without normalization
[[1492    0    0    0    3]
 [   0 1503    0    3    0]
 [   0    0 1453    1    4]
 [   0    1    1 1533    2]
 [   4   30   10   19 1441]]
Normalized confusion matrix
[[9.98e-01 0.00e+00 0.00e+00 0.00e+00 2.01e-03]
 [0.00e+00 9.98e-01 0.00e+00 1.99e-03 0.00e+00]
 [0.00e+00 0.00e+00 9.97e-01 6.86e-04 2.74e-03]
 [0.00e+00 6.51e-04 6.51e-04 9.97e-01 1.30e-03]
 [2.66e-03 1.99e-02 6.65e-03 1.26e-02 9.58e-01]]
              precision    recall  f1-score   support

           0       1.00      1.00      1.00      1495
           1       0.98      1.00      0.99      1506
           2       0.99      1.00      0.99      1458
           3       0.99      1.00      0.99      1537
           4       0.99      0.96      0.98      1504

    accuracy                           0.99      7500
   macro avg       0.99      0.99      0.99      7500
weighted avg       0.99      0.99      0.99      7500



In [30]:
#Need to change shape of data (keras conventional input) for convolutional neural network
trainX=np.reshape(trainX,(-1,300,1))
testX=np.reshape(testX,(-1,300,1))
print(trainX.shape)
print(testX.shape)

(17500, 300, 1)
(7500, 300, 1)


In [33]:
#Make a simple CNN (other way)
input_tensor=Input((300,1))

#Adding convolutional layers
conv=Conv1D(filters=64,kernel_size=3, strides=1, padding='valid')(input_tensor)
actv=Activation("relu")(conv)
maxP=MaxPooling1D(pool_size=2)(actv)

conv=Conv1D(filters=32,kernel_size=5, strides=2, padding='same')(maxP)
actv=Activation(keras.activations.relu)(conv)
maxP=MaxPooling1D(pool_size=2)(actv)

#flattening the nd-array to 1d-array
f_vector=Flatten()(maxP)

#Add Dense layers- Artificial Neural Network
dense=Dense(units=500)(f_vector)
actv=Activation(keras.activations.relu)(dense)
dense=Dense(units=100)(actv)
actv=Activation(keras.activations.relu)(dense)
dense=Dense(units=5)(actv)
out=Activation(keras.activations.softmax)(dense)

#Combine all layers in Model Object
cnn_classifier=Model(inputs=input_tensor,outputs=out)
cnn_classifier.compile(optimizer = 'adam', loss = 'categorical_crossentropy', metrics = ['accuracy'])

In [34]:
cnn_classifier.summary()

_________________________________________________________________
Layer (type)                 Output Shape              Param #   
input_2 (InputLayer)         (None, 300, 1)            0         
_________________________________________________________________
conv1d_3 (Conv1D)            (None, 298, 64)           256       
_________________________________________________________________
activation_6 (Activation)    (None, 298, 64)           0         
_________________________________________________________________
max_pooling1d_3 (MaxPooling1 (None, 149, 64)           0         
_________________________________________________________________
conv1d_4 (Conv1D)            (None, 75, 32)            10272     
_________________________________________________________________
activation_7 (Activation)    (None, 75, 32)            0         
_________________________________________________________________
max_pooling1d_4 (MaxPooling1 (None, 37, 32)            0         
__________

In [35]:
#training a classifier i.e. making it learn to differentiate between 1 normal and 4 abnormal classes
cnn_classifier.fit(trainX, trainY, batch_size = 100, epochs = 10, verbose=1,
          validation_data=(testX, testY))

Train on 17500 samples, validate on 7500 samples
Epoch 1/10
17500/17500 [==============================] - 10s 572us/step - loss: 0.1871 - acc: 0.9458 - val_loss: 0.0525 - val_acc: 0.9856
Epoch 2/10
17500/17500 [==============================] - 7s 414us/step - loss: 0.0406 - acc: 0.9893 - val_loss: 0.0455 - val_acc: 0.9844
Epoch 3/10
17500/17500 [==============================] - 7s 423us/step - loss: 0.0223 - acc: 0.9938 - val_loss: 0.0181 - val_acc: 0.9943
Epoch 4/10
17500/17500 [==============================] - 7s 416us/step - loss: 0.0135 - acc: 0.9957 - val_loss: 0.0176 - val_acc: 0.9933
Epoch 5/10
17500/17500 [==============================] - 7s 418us/step - loss: 0.0097 - acc: 0.9971 - val_loss: 0.0158 - val_acc: 0.9956
Epoch 6/10
17500/17500 [==============================] - 8s 433us/step - loss: 0.0052 - acc: 0.9986 - val_loss: 0.0144 - val_acc: 0.9955
Epoch 7/10
17500/17500 [==============================] - 7s 424us/step - loss: 0.0089 - acc: 0.9970 - val_loss: 0.0194 - 

In [36]:
#save classifier
cnn_classifier.save('cnn_classifier.h5')

In [37]:
from sklearn.metrics import classification_report,confusion_matrix
predY=cnn_classifier.predict(testX)
predY=np.argmax(predY,axis=1)
testY1=np.argmax(testY,axis=1)

                        #Compute Confusion Matrix
cm=confusion_matrix(testY1,predY)
np.set_printoptions(precision=2)
print('Confusion matrix, without normalization')
print(cm)
                        #Compute Normalized Confusion Matrix
cm_normalized=cm.astype('float')/cm.sum(axis=1)[:, np.newaxis]
print('Normalized confusion matrix')
print(cm_normalized)

                        #ANN  Classification report
ann_classification_report=classification_report(testY1,predY)
print(ann_classification_report)

Confusion matrix, without normalization
[[1493    0    1    0    1]
 [   0 1504    0    2    0]
 [   0    0 1455    0    3]
 [   0    0    0 1534    3]
 [   2    3    3   16 1480]]
Normalized confusion matrix
[[9.99e-01 0.00e+00 6.69e-04 0.00e+00 6.69e-04]
 [0.00e+00 9.99e-01 0.00e+00 1.33e-03 0.00e+00]
 [0.00e+00 0.00e+00 9.98e-01 0.00e+00 2.06e-03]
 [0.00e+00 0.00e+00 0.00e+00 9.98e-01 1.95e-03]
 [1.33e-03 1.99e-03 1.99e-03 1.06e-02 9.84e-01]]
              precision    recall  f1-score   support

           0       1.00      1.00      1.00      1495
           1       1.00      1.00      1.00      1506
           2       1.00      1.00      1.00      1458
           3       0.99      1.00      0.99      1537
           4       1.00      0.98      0.99      1504

    accuracy                           1.00      7500
   macro avg       1.00      1.00      1.00      7500
weighted avg       1.00      1.00      1.00      7500

